/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicFilterTableTemp: typeof import('./src/components/basic-filter-table-temp/index.vue')['default']
    ButtonGroup: typeof import('./src/components/button-group/index.vue')['default']
    CommonDialog: typeof import('./src/components/common-dialog/index.vue')['default']
    CommonTable: typeof import('./src/components/common-table/index.vue')['default']
    Echarts: typeof import('./src/components/echarts/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FilterConfig: typeof import('./src/components/filter-config/index.vue')['default']
    ItemInput: typeof import('./src/components/common/form-item/item-input.vue')['default']
    ItemRadio: typeof import('./src/components/common/form-item/item-radio.vue')['default']
    ItemSelect: typeof import('./src/components/common/form-item/item-select.vue')['default']
    ItemTimeSelect: typeof import('./src/components/common/form-item/item-time-select.vue')['default']
    ItemUpload: typeof import('./src/components/common/form-item/item-upload.vue')['default']
    PremissionTree: typeof import('./src/components/premissionTree/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowDescription: typeof import('./src/components/common-table/operating/rowDescription.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
